// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZUjO3_Bz93572tQqFSN7td1pabLfN-iw',
    appId: '1:339336551842:web:79f1fee0c96914145f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    authDomain: 'anany-me.firebaseapp.com',
    storageBucket: 'anany-me.appspot.com',
    measurementId: 'G-3BPDEGB72J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpzH2MUTMPlJEofF-x1P7PC-BDDUK6zo',
    appId: '1:339336551842:android:e2da6ef12f1f883b5f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    storageBucket: 'anany-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVKD-66zHFfII8az_LCruXcNwwSzmLjU',
    appId: '1:339336551842:ios:7a3054136d0596ad5f66fb',
    messagingSenderId: '339336551842',
    projectId: 'anany-me',
    storageBucket: 'anany-me.appspot.com',
    iosBundleId: 'com.example.tStore',
  );
}
