// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMLGKR8jIFqwk2qIjTG7Ep0EBaHFpIOKM',
    appId: '1:202259476090:web:091155b7e88acc171d55c3',
    messagingSenderId: '202259476090',
    projectId: 'base-firebase-67851',
    authDomain: 'base-firebase-67851.firebaseapp.com',
    storageBucket: 'base-firebase-67851.appspot.com',
    measurementId: 'G-Z7GE38XF1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1XVX4Vt1ZFhtJ36VBda8rRpIyoxwo_0',
    appId: '1:202259476090:android:8c2f37b6bb03f5de1d55c3',
    messagingSenderId: '202259476090',
    projectId: 'base-firebase-67851',
    storageBucket: 'base-firebase-67851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIsDl5FUw7BgDonwWzV2j8BNFep4BKLxM',
    appId: '1:202259476090:ios:6bc2bedf5eccc0eb1d55c3',
    messagingSenderId: '202259476090',
    projectId: 'base-firebase-67851',
    storageBucket: 'base-firebase-67851.appspot.com',
    androidClientId: '202259476090-eqso31rgpdoeb0kbihupc16a4931pevp.apps.googleusercontent.com',
    iosClientId: '202259476090-nqhor606sncuc25rv6131s6e7odag1uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
